# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.runs/synth_1/RISCV_Black_Box_Translator.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xck26-sfvc784-2LV-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.cache/wt [current_project]
set_property parent.project_path C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:kv260:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -vhdl2008 -library riscv {
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/ALU.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Acumulator.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/CSR/CSR_MARCHID_REG.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/CSR/CSR_MISA_REG.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/CSR/CSR_MVENDORID_REG.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/CSR/CSR_TIMER.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Mux/mux_32_32.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/DEMUX_32_1.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/CSR/CSR_TIMER_ARRAY.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/CSR/CSR_hpmcounter.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/CSR/CSR_Regfile.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Register/reg3b.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Register/reg1b.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Register/reg2b.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Register/reg5b.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Register/reg12b.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Register/reg32b.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Stage/EX_MEM_DIV.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Mux/mux_2_1.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/adder.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/jump_target_unit.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/forwarding_unit.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/forwarding_unit_CSR.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Mux/mux_5_1.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Mux/mux_3_1.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Mux/mux_4_1.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Stage/EX_STAGE.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Register/reg4b.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Stage/ID_EX_DIV.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/controller.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Register/reg32b_falling_edge.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Mux/mux_32_1.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/register_file.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Stage/ID_STAGE.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Stage/IF_ID_DIV.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/progmem_interface.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/program_counter.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Stage/IF_STAGE.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/INTERRUPT_CONTROL_UNIT.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/flushing_unit.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Stage/MEM_WB_DIV.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/datamem_interface.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Stage/MEM_STAGE.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Stage/WB_STAGE.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/MCU2.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/Slider_mux.vhd
  C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/sources_1/imports/new/RISCV_Black_Box_Translator.vhd
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/constrs_1/new/master.xdc
set_property used_in_implementation false [get_files C:/Users/Brice/Documents/GitHub/RISC-V-Completion-project/project_2.srcs/constrs_1/new/master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top RISCV_Black_Box_Translator -part xck26-sfvc784-2LV-c
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RISCV_Black_Box_Translator.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RISCV_Black_Box_Translator_utilization_synth.rpt -pb RISCV_Black_Box_Translator_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
